import { useEffect, useState } from 'react';
import { useNavigate, useOutletContext, useLocation } from 'react-router-dom';
import { api } from '../api';

const STATUS_BADGES = {
  draft: 'bg-slate-700/60 text-slate-300',
  'pending approval': 'bg-amber-500/20 text-amber-300 border border-amber-500/30',
  approved: 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30',
  rejected: 'bg-rose-500/20 text-rose-300 border border-rose-500/30',
  active: 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/30',
  completed: 'bg-blue-500/20 text-blue-300 border border-blue-500/30',
  expired: 'bg-slate-600/40 text-slate-400',
};

export default function SupplyPlanHistory() {
  const { profile } = useOutletContext() || {};
  const navigate = useNavigate();
  const location = useLocation();
  const supplyBase = location.pathname.startsWith('/operator') ? '/operator/supply-planning' : '/dashboard/supply-planning';
  const role = String(profile?.role || '').toLowerCase();
  const isOrg = role === 'organization';

  const [items, setItems] = useState([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState('');
  const [dateFilter, setDateFilter] = useState('');
  const limit = 15;

  useEffect(() => {
    setLoading(true);
    const params = { page, limit };
    if (statusFilter) params.status = statusFilter;
    if (dateFilter) params.date = dateFilter;
    api.get('/supply-plans', { params })
      .then(res => { setItems(res.data.items || []); setTotal(res.data.total || 0); })
      .catch(() => setItems([]))
      .finally(() => setLoading(false));
  }, [page, statusFilter, dateFilter]);

  const statusOptions = isOrg
    ? ['approved', 'active', 'completed']
    : ['draft', 'pending approval', 'approved', 'rejected', 'active', 'completed', 'expired'];

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Plan History</h1>
          <p className="text-sm text-slate-400">All supply plans · {total} total</p>
        </div>
        <div className="flex items-center gap-3">
          <input
            type="date"
            value={dateFilter}
            onChange={e => { setDateFilter(e.target.value); setPage(1); }}
            className="rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100"
          />
          <select value={statusFilter} onChange={e => { setStatusFilter(e.target.value); setPage(1); }}
            className="rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100">
            <option value="">All Statuses</option>
            {statusOptions.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
          <button onClick={() => navigate(supplyBase)}
            className="rounded-xl bg-cyan-500/20 border border-cyan-500/30 px-4 py-2 text-sm font-semibold text-cyan-300 hover:bg-cyan-500/30">
            ← Today's Plan
          </button>
        </div>
      </div>

      <div className="rounded-2xl border border-slate-700/60 bg-slate-900/70 overflow-hidden">
        {loading ? (
          <div className="flex justify-center py-16">
            <div className="h-8 w-8 animate-spin rounded-full border-4 border-cyan-400 border-t-transparent" />
          </div>
        ) : items.length === 0 ? (
          <div className="py-16 text-center text-slate-400">No plans found.</div>
        ) : (
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-slate-700/60">
                {['Date', 'Port', 'Status', 'Efficiency', 'Coverage', 'Generated By', 'Actions'].map(h => (
                  <th key={h} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {items.map((plan, i) => (
                <tr key={plan._id} className={`border-b border-slate-800/60 hover:bg-slate-800/30 transition ${i % 2 === 0 ? '' : 'bg-slate-800/10'}`}>
                  <td className="px-4 py-3 font-medium text-white">{plan.planDate}</td>
                  <td className="px-4 py-3 text-slate-300">{plan.portName}</td>
                  <td className="px-4 py-3">
                    <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider ${STATUS_BADGES[plan.status] || 'bg-slate-700 text-slate-300'}`}>
                      {plan.status}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-slate-300">{plan.metrics?.planEfficiencyScore?.toFixed(1) ?? '—'}/100</td>
                  <td className="px-4 py-3 text-slate-300">{plan.metrics?.demandCoveragePercentage?.toFixed(1) ?? '—'}%</td>
                  <td className="px-4 py-3">
                    <span className={`rounded-full px-2 py-0.5 text-[10px] uppercase font-semibold ${plan.generatedBy === 'AI' ? 'bg-cyan-500/20 text-cyan-300' : 'bg-slate-700 text-slate-400'}`}>
                      {plan.generatedBy}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <button
                      onClick={() => navigate(supplyBase, { state: { planId: plan._id, date: plan.planDate } })}
                      className="rounded-lg bg-slate-700 px-3 py-1 text-xs text-slate-300 hover:bg-slate-600"
                    >
                      View
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Pagination */}
      {total > limit && (
        <div className="flex justify-center gap-2">
          <button disabled={page === 1} onClick={() => setPage(p => p - 1)}
            className="rounded-xl bg-slate-800 px-4 py-2 text-sm text-slate-300 disabled:opacity-40 hover:bg-slate-700">← Prev</button>
          <span className="px-3 py-2 text-sm text-slate-400">Page {page} of {Math.ceil(total / limit)}</span>
          <button disabled={page * limit >= total} onClick={() => setPage(p => p + 1)}
            className="rounded-xl bg-slate-800 px-4 py-2 text-sm text-slate-300 disabled:opacity-40 hover:bg-slate-700">Next →</button>
        </div>
      )}
    </div>
  );
}
